SELECT PRODUCT_CODE, PR.PRICE * SUM(OS.SALES_AMOUNT) AS SALES 
FROM PRODUCT AS PR INNER JOIN OFFLINE_SALE AS OS
WHERE PR.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE
