SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * SUM(FO.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP, FOOD_ORDER AS FO
WHERE MONTH(FO.PRODUCE_DATE) = "5" AND YEAR(FO.PRODUCE_DATE) = "2022" AND FP.PRODUCT_ID = FO.PRODUCT_ID
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID
