SELECT FP1.CATEGORY, FP1.PRICE AS MAX_PRICE, FP1.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP1 INNER JOIN 
    (SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY)
    AS FP2
WHERE FP1.CATEGORY = FP2.CATEGORY AND FP1.PRICE = FP2.PRICE AND FP1.CATEGORY IN ("과자", "국", "김치", "식용유")
ORDER BY MAX_PRICE DESC
