SET @HOUR = -1;
SELECT AO1.HOUR, IFNULL(COUNT, 0) 
FROM
    (SELECT @HOUR := @HOUR + 1 AS HOUR
     FROM ANIMAL_OUTS
     WHERE @HOUR < 23) AS AO1
     LEFT OUTER JOIN
     (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
      FROM ANIMAL_OUTS
      GROUP BY HOUR(DATETIME)) AS AO2
     ON AO1.HOUR = AO2.HOUR
ORDER BY AO1.HOUR
