SELECT BA.AUTHOR_ID, AUTHOR_NAME, BA.CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM
(SELECT BOOK_ID, BOOK.AUTHOR_ID, CATEGORY, AUTHOR_NAME, PRICE
FROM BOOK INNER JOIN AUTHOR ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID) AS BA
INNER JOIN
(SELECT BOOK.BOOK_ID, CATEGORY, AUTHOR_ID, SUM(SALES) AS SALES
FROM BOOK INNER JOIN BOOK_SALES ON SALES_DATE LIKE '2022-01%' AND BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
GROUP BY BOOK.BOOK_ID) AS BB
ON BA.BOOK_ID = BB.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
