SELECT FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
      FROM FIRST_HALF 
      GROUP BY FLAVOR
      UNION 
      SELECT FLAVOR, TOTAL_ORDER
      FROM JULY ) 
      AS TOTAL
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC LIMIT 3
